# Generated by Django 6.0.6 on 2026-06-16 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id_escola', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ATIVADA', 'Ativada'), ('DESATIVADA', 'Desativada'), ('EXCLUIDA', 'Excluída')], default='ATIVADA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Escolas',
                'db_table': 'escolas',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('propina_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEscola',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('moeda', models.CharField(default='AOA', max_length=10)),
                ('permitir_atraso', models.BooleanField(default=True)),
                ('dias_tolerancia', models.IntegerField(default=5)),
                ('id_escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
            options={
                'verbose_name_plural': 'Configurações de Escola',
                'db_table': 'configuracoes_escola',
            },
        ),
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id_bolsa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo_bolsa', models.CharField(blank=True, max_length=50, null=True)),
                ('percentual_desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
            options={
                'verbose_name_plural': 'Bolsas',
                'db_table': 'bolsas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('periodo', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=20)),
                ('ano_letivo', models.IntegerField(blank=True, null=True)),
                ('sala', models.IntegerField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.curso')),
                ('id_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'db_table': 'turmas',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('numero_aluno', models.IntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone_encarregado', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Ativo'), ('INACTIVO', 'Inativo'), ('TRANSFERIDO', 'Transferido')], default='ACTIVO', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('id_bolsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bolsa')),
                ('id_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma')),
            ],
            options={
                'verbose_name_plural': 'Alunos',
                'db_table': 'alunos',
                'unique_together': {('numero_aluno', 'id_turma')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('senha', models.CharField(max_length=255)),
                ('cargo', models.CharField(choices=[('ADMIN', 'Administrador'), ('FINANCEIRO', 'Financeiro'), ('RECEPCAO', 'Recepção')], max_length=30)),
                ('estado', models.CharField(choices=[('ATIVADO', 'Ativado'), ('DESATIVADO', 'Desativado')], default='ATIVADO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
                'unique_together': {('id_escola', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(blank=True, max_length=100, null=True)),
                ('tabela_afetada', models.CharField(blank=True, max_length=100, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
            ],
            options={
                'verbose_name_plural': 'Auditorias',
                'db_table': 'auditoria',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('valor_propina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('metodo_pagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
            ],
            options={
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pagamentos',
                'unique_together': {('id_aluno', 'mes', 'ano')},
            },
        ),
    ]
